name: Python Experiment Test CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.x'
          cache: 'pip'

      - name: Install dependencies
        run: | 
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd experiment
          python -m unittest
